name: Node CI

on:
  pull_request:
    branches: [ main ]
env:
  NODE_VERSION: 18.x

jobs:
  install:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: yarn

    - run: corepack enable
    - name: Install
      run: yarn install --frozen-lockfile
  
  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: yarn

    - run: corepack enable
    - name: Install
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: yarn

    - run: corepack enable
    - name: Install
      run: yarn install --frozen-lockfile

    - name: Lint
      run: yarn lint