name: Update Changelog

on:
  release:
    types: 
      - published

env:
  NODE_VERSION: 18.x

jobs:
  update:
    name: Update Changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Update package.json version
        uses: jaywcjlove/github-action-package@main
        with:
          version: ${{ github.event.release.name }}

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          release-notes: ${{ github.event.release.body }}
          latest-version: ${{ github.event.release.name }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: 'ci: update version to ${{ github.event.release.name }} [skip ci]'
          push_options: --force

  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: update
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
          cache: yarn
      
      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build package
        run: yarn build:all

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}